# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: XUNGE's Blog
subtitle: 训哥的故事
description: 瞎折腾，知识点，经验值
author: 训哥
email: 1063563945@qq.com
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://xungejiang.com
root: /
# permalink: archives/:title.html
permalink: /:year/:month/:day/:title/
permalink_defaults: :title.html

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: :lang
skip_render: 
  - static/**
  - search.html
  - 404.html

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: true

# Category & Tag
default_category: 瞎折腾
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
index_generator:
  per_page: 10
  order_by: -date

category_generator:
  per_page: 0

tag_generator:
  per_page: 0

archive_generator:
  per_page: 0
  yearly: true
  monthly: true
  daily: false
pagination_dir: page

include:
  - .htaccess
  - robots.txt

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-vanilla
# theme: indigo
# theme: hexo-theme-material

search:
    path: search.json
    field: post

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 0
    
# Sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:xunge/xunge.github.io.git
    coding: git@git.coding.net:xunge/xunge.github.io.git
    # aliyun: git@101.132.124.235:/home/git/blog.git

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'solarizedlight'
  line_number: false    # default false

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true