# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: XUNGE's Blog
subtitle: 训哥的故事
description: 瞎折腾，知识点，经验值
author: 训哥
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://xungejiang.com
root: /
permalink: archives/:title.html
permalink_defaults: :title.html

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: :lang
skip_render: 
  - static/**
  - search.html
  - 404.html

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false

# Category & Tag
default_category: 瞎折腾
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
index_generator:
  per_page: 5
  order_by: -date

category_generator:
  per_page: 0

tag_generator:
  per_page: 0

archive_generator:
  per_page: 0
  yearly: true
  monthly: true
  daily: false
pagination_dir: page

include:
  - .htaccess
  - robots.txt

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-spectre

search:
    path: search.json
    field: post

# RSS
feed:
    type: rss2
    path: rss.xml
    limit: 0
    hub:
    content: true
    
# Sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:xunge/xunge.github.io.git

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'solarizedlight'
  line_number: true    # default false
