# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
  favicon: "https://img.xungejiang.com/static/images/favicon.png"
  high_res_favicon: "https://img.xungejiang.com/static/images/favicon.png"
  apple_touch_icon: "https://img.xungejiang.com/static/images/favicon.png"
  keywords: "xungejiang, blog, hexo, Web, 博客, xunge, 训哥"
  site_verification:
    google: 
    baidu:

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Theme Color
color:
  android_chrome_color: "#455A64"

# ---------------------------------------------------------------
# Customsize Settings
# ---------------------------------------------------------------

# Jump Links Settings
url:
  rss: /rss.xml
  sitemap: /sitemap.xml
  daily_pic: ""
  logo: "https://xungejiang.com"

# Images Settings
img:
  logo: https://img.xungejiang.com/static/images/avatar1.jpg
  avatar: https://img.xungejiang.com/static/images/avatar1.jpg
  daily_pic: https://img.xungejiang.com/static/images/banner1.jpg


# Slogan (will show at daily_pic)
slogan: "训羽，智欣"

# Posts Settings
post:
    entry_excerpt: 100

    # Qrcode for redirect at other device
    #    use: choose which method to generate the qrcode for each posts.
    #        Available value: plugin | online
    #            - When use "plugin", you need to install the hexo-helper-qrcode.
    #            - When use "online", the qrcode will be generated by 'pan.baidu.com' in Mainland China,
    #               and generated by 'charts.googleapis.com' in other areas.
    qrcode:
      enable: true
      use: plugin

    # Post License
    # You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
    #   For example, you can setup a CC license as:
    #       'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
    # You can also use Front-Matter `license` to override this setting.
    license: "本文采用 <a rel='nofollow noopener' href='https://creativecommons.org/licenses/by-nc-sa/3.0/deed.zh' target='_blank'>CC BY-NC-SA 3.0 Unported</a> 协议进行许可，阅读 <a href='/creativecommons.html' target='_blank'>相关说明</a>"

# Footer Settings
footer:
  # Footer Copyright
  # Specify the date when the site was setup.
  #    For example, if you set it as 2015, then footer will show '© 2015 - 2017'
  copyright_since: 2016
  footer_text: '<div><a href="http://beian.miit.gov.cn" rel="nofollow">黑ICP备18006891号</a></div>'

  # FooterSNS Icon
  sns:
    facebook:
    twitter:
    googleplus:
    weibo:
    instagram:
    tumblr:
    github: https://github.com/xunge
    linkedin:
    zhihu: https://www.zhihu.com/people/jiang-xun-zhi-17
    bilibili:
    telegram: 
    v2ex: 

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: true
    qq: true
    telegram: true

# Sidebar Customize
sidebar:
  homepage:
    use: true
    icon: home
    divider: false
  search:
    use: true
    icon: search
    divider: false
  archives:
    use: true
    icon: inbox
    divider: false
  categories:
    use: false
    icon: chrome_reader_mode
    divider: false
  pages:
    标签:
      link: "/tags.html"
      icon: bookmark
      divider: false
    关于:
      link: "/about.html"
      icon: person
      divider: false
    友链:
      link: "/links.html"
      icon: people
      divider: true
  article_num:
    use: true
    divider: false
  footer:
    

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value of "use":
#   disqus | disqus_click | changyan | livere | gitment | valine
# If you want to use gitment,you should get the client_id and client_secret form https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key form https://leancloud.cn ,more setting please see https://github.com/xCss/Valine
comment:
  use: disqus_click
  shortname: xungejiang-com # duoshuo or disqus shortname
  changyan_appid:
  changyan_conf:
  changyan_thread_key_type: path
  livere_data_uid:
  gitment_repo:   # git repo of the hexo
  gitment_owner:  # git repo's owner
  gitment_client_id:  # github app client id 
  gitment_client_secret :  # github app client secret 
  valine_leancloud_appId: # leancloud application app id
  valine_leancloud_appKey: # leancloud application app key

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

mathjax:
   enable: true

# ---------------------------------------------------------------
# Do Not Edit Below This Line, unless you know what you are doing!
# ---------------------------------------------------------------
verison: 1.0.0
old_verison:
  - 1.4.0
  - 1.5.0

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true